webappexample/accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"
urlpatterns = [
    path("login", views.login, name="login"),
    path("callback", views.callback, name="callback"),
    path("logout", views.logout, name="logout"),
]

webappexample/myapp/urls.py
from django.urls import path

from myapp import views

app_name = "myapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

webappexample/webappexample/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("myapp.urls")),
]

webappexample/accounts/views.py
from urllib.parse import quote_plus, urlencode

from authlib.integrations.django_client import OAuth
from django.shortcuts import redirect
from django.conf import settings
from django.urls import reverse

oauth = OAuth()
oauth.register(
    "auth0",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    client_kwargs={"scope": "openid profile email"},
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)


def login(request):
    return oauth.auth0.authorize_redirect(
        request, request.build_absolute_uri(reverse("accounts:callback"))
    )


def callback(request):
    token = oauth.auth0.authorize_access_token(request)
    request.session["user"] = token
    return redirect(request.build_absolute_uri(reverse("myapp:index")))


def logout(request):
    request.session.clear()

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("myapp:index")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        )
    )

webappexample/myapp/views.py
import json

from django.contrib.auth.views import redirect_to_login
from django.shortcuts import render
from django.urls import reverse


def index(request):
    return render(
        request,
        "myapp/index.html",
        context={
            "session": request.session.get("user"),
            "pretty": json.dumps(request.session.get("user"), indent=4),
        },
    )


def dashboard(request):
    if not request.session.get("user"):
        return redirect_to_login(
            request.build_absolute_uri(), reverse("accounts:login")
        )

    return render(request, "myapp/dashboard.html")

webappexample/accounts/templates/accounts/index.html
<html>

<head>
    <meta charset="utf-8" />
    <title>Auth0 Example</title>
</head>

<body>
    {% if session %}
    <h1>Welcome {{ session.userinfo.name }}!</h1>
    <p><a href="{% url 'logout' %}">Logout</a></p>
    <div>
        <pre>{{ pretty }}</pre>
    </div>
    {% else %}
    <h1>Welcome Guest</h1>
    <p><a href="{% url 'login' %}">Login</a></p>
    {% endif %}
</body>

</html>

webappexample/myapp/templates/myapp/dashboard.html
<!DOCTYPE html>
<html>

<head>
    <title>Dashboard</title>
</head>

<body>
    <h1>Welcome to the Dashboard</h1>
    <p>Hello, {{ request.session.user.userinfo.nickname }}!</p>
    <p><a href="{% url 'myapp:index' %}">Home</a></p>
</body>

</html>

webappexample/myapp/templates/myapp/index.html
<html>

<head>
    <meta charset="utf-8" />
    <title>Auth0 Example</title>
</head>

<body>
    {% if session %}
    <h1>Welcome {{ session.userinfo.name }}!</h1>
    <p><a href="{% url 'myapp:dashboard' %}">Go to Dashboard</a></p>
    <p><a href="{% url 'accounts:logout' %}">Logout</a></p>
    <div>
        <pre>{{ pretty }}</pre>
    </div>
    {% else %}
    <h1>Welcome Guest</h1>
    <p><a href="{% url 'accounts:login' %}">Login</a></p>
    {% endif %}
</body>

</html>